# Vulture dead-code allowlist (machine-generated baseline).
#
# Regenerate with:  vulture src --make-whitelist > vulture_allowlist.py
# (then re-add this header). The `[tool.vulture]` paths in pyproject.toml feed
# this file back into the scan so every name below counts as "used", giving a
# clean gate on the current tree. `make deadcode` / the pre-commit hook fail
# only on NEW dead code introduced after this baseline.
#
# This baseline was reviewed (see HISTORY.md 2026-07-23 and TASKS.md): the
# entries are Textual/Peewee/CoreAudio framework false-positives and symbols
# used dynamically (registry strings, by-name dispatch, test-only helpers,
# persisted StrEnum members). A clean-pass audit found 16 genuinely-dead
# symbols inside this set; 15 were deleted on 2026-07-25 (verified against
# on-disk use, each with its callee/import cascades). That count includes the
# abandoned TUI-self-generate briefing slice (_generate_briefing_worker + the
# injected _briefing_generator attr/param + cli._briefing_generator_for_launch),
# an older design superseded by the runner-produces-artifact / TUI-adopts path
# (_adopt_owed_briefing_worker) that is actually wired live.
# One symbol is HELD — run_briefing_via_runner — the not-yet-wired submit
# trigger for that runner-artifact briefing pipeline. It is kept dormant on
# purpose: the pipeline (JobKind.COMPACT_BRIEFING + its DB CHECK constraint,
# handle_briefing, briefing_artifacts, and the live adopt path) stays, so
# removing the trigger would be a schema migration, not a mechanical delete.
#
# ruff excludes this file (extend-exclude) — bare names here are F821 to ruff.

QUEUE_FILE  # unused variable (src/wilted/__init__.py:24)
_chunk_segments  # unused function (src/wilted/ads.py:697)
remove_promos_batch  # unused function (src/wilted/ads.py:1540)
PAUSED  # unused variable (src/wilted/background_work/contracts.py:43)
report_decision  # unused variable (src/wilted/background_work/legacy_mapping.py:84)
all_processing_job_transition_pairs  # unused function (src/wilted/background_work/transitions.py:68)
requested  # unused variable (src/wilted/background_work/transitions.py:117)
observed_at  # unused variable (src/wilted/background_work/transitions.py:118)
all_runner_transition_pairs  # unused function (src/wilted/background_work/transitions.py:243)
load_audio  # unused function (src/wilted/cache.py:50)
is_paragraph_cached  # unused function (src/wilted/cache.py:100)
run_classify  # unused function (src/wilted/classify.py:219)
Meta  # unused class (src/wilted/db.py:186)
last_checked_at  # unused variable (src/wilted/db.py:204)
updated_at  # unused variable (src/wilted/db.py:208)
Meta  # unused class (src/wilted/db.py:210)
table_name  # unused variable (src/wilted/db.py:211)
Meta  # unused class (src/wilted/db.py:225)
table_name  # unused variable (src/wilted/db.py:226)
tags  # unused variable (src/wilted/db.py:296)
Meta  # unused class (src/wilted/db.py:303)
table_name  # unused variable (src/wilted/db.py:304)
constraints  # unused variable (src/wilted/db.py:305)
indexes  # unused variable (src/wilted/db.py:306)
Meta  # unused class (src/wilted/db.py:322)
table_name  # unused variable (src/wilted/db.py:323)
added_at  # unused variable (src/wilted/db.py:331)
Meta  # unused class (src/wilted/db.py:334)
table_name  # unused variable (src/wilted/db.py:335)
constraints  # unused variable (src/wilted/db.py:336)
Meta  # unused class (src/wilted/db.py:347)
table_name  # unused variable (src/wilted/db.py:348)
Meta  # unused class (src/wilted/db.py:371)
table_name  # unused variable (src/wilted/db.py:372)
constraints  # unused variable (src/wilted/db.py:373)
indexes  # unused variable (src/wilted/db.py:374)
Meta  # unused class (src/wilted/db.py:384)
table_name  # unused variable (src/wilted/db.py:385)
Meta  # unused class (src/wilted/db.py:398)
table_name  # unused variable (src/wilted/db.py:399)
constraints  # unused variable (src/wilted/db.py:400)
updated_at  # unused variable (src/wilted/db.py:430)
Meta  # unused class (src/wilted/db.py:449)
table_name  # unused variable (src/wilted/db.py:450)
indexes  # unused variable (src/wilted/db.py:451)
ALL_MODELS  # unused variable (src/wilted/db.py:461)
Meta  # unused class (src/wilted/db.py:486)
table_name  # unused variable (src/wilted/db.py:487)
_.current_segment_idx  # unused attribute (src/wilted/engine.py:72)
_._sample_offset  # unused attribute (src/wilted/engine.py:73)
_._sample_offset  # unused attribute (src/wilted/engine.py:95)
_._sample_offset  # unused attribute (src/wilted/engine.py:116)
_._sample_offset  # unused attribute (src/wilted/engine.py:157)
_._sample_offset  # unused attribute (src/wilted/engine.py:178)
_.play_audio  # unused method (src/wilted/engine.py:218)
_.generate_and_play  # unused method (src/wilted/engine.py:229)
_.current_segment_idx  # unused attribute (src/wilted/engine.py:393)
_.current_segment_idx  # unused attribute (src/wilted/engine.py:571)
_.is_playing  # unused property (src/wilted/engine.py:700)
_.is_paused  # unused property (src/wilted/engine.py:705)
_.updated_at  # unused attribute (src/wilted/feeds.py:168)
get_feed  # unused function (src/wilted/feeds.py:175)
extract_title_from_url  # unused function (src/wilted/fetch.py:103)
run_article_cache_via_runner  # unused function (src/wilted/pipeline_submit.py:496)
run_briefing_via_runner  # unused function (src/wilted/pipeline_submit.py:713)
run_expiry  # unused function (src/wilted/playlists.py:313)
get_resume_position  # unused function (src/wilted/playlists.py:384)
set_resume_position  # unused function (src/wilted/playlists.py:420)
clear_resume_position  # unused function (src/wilted/playlists.py:461)
run_prepare  # unused function (src/wilted/prepare.py:535)
claim_next_job  # unused function (src/wilted/processing_jobs.py:268)
request_cancel  # unused function (src/wilted/processing_jobs.py:320)
get_job  # unused function (src/wilted/processing_jobs.py:821)
transition_job_state  # unused function (src/wilted/processing_jobs.py:886)
run_retention  # unused function (src/wilted/queue.py:309)
run_report  # unused function (src/wilted/report.py:121)
_.from_rss_chapters  # unused method (src/wilted/station/models.py:174)
_.from_verified_windows  # unused method (src/wilted/station/models.py:189)
_.nearest_safe_point  # unused method (src/wilted/station/models.py:213)
_.is_checkpointable  # unused property (src/wilted/station/models.py:347)
_.current_checkpoint  # unused method (src/wilted/station/protocols.py:51)
_.persist_checkpoint  # unused method (src/wilted/station/protocols.py:55)
_.append_event  # unused method (src/wilted/station/protocols.py:65)
_.persist_lease  # unused method (src/wilted/station/protocols.py:73)
CHECKPOINTED  # unused variable (src/wilted/station/reducer.py:43)
PAUSED_ON_MAC  # unused variable (src/wilted/station/reducer.py:45)
_.ensure_fresh  # unused method (src/wilted/station_runtime/briefing.py:560)
revision  # unused variable (src/wilted/station_runtime/controller.py:139)
_.held_epoch  # unused property (src/wilted/station_runtime/controller.py:355)
_.is_lost  # unused property (src/wilted/station_runtime/controller.py:365)
_.peak_concurrent_residency  # unused property (src/wilted/station_runtime/coordinator.py:284)
_._read_heartbeat  # unused method (src/wilted/station_runtime/lease.py:323)
_.held_epoch  # unused property (src/wilted/station_runtime/lease.py:514)
_.is_lease_live  # unused method (src/wilted/station_runtime/lease.py:519)
get_owners  # unused function (src/wilted/station_runtime/media_store.py:346)
_.last_completion  # unused property (src/wilted/station_runtime/playback_adapter.py:224)
_.current_device  # unused method (src/wilted/station_runtime/route_monitor.py:82)
in_addresses  # unused variable (src/wilted/station_runtime/route_monitor.py:356)
in_client_data  # unused variable (src/wilted/station_runtime/route_monitor.py:356)
in_number_addresses  # unused variable (src/wilted/station_runtime/route_monitor.py:356)
in_object_id  # unused variable (src/wilted/station_runtime/route_monitor.py:356)
_.current_device  # unused method (src/wilted/station_runtime/route_monitor.py:401)
_.current_checkpoint  # unused method (src/wilted/station_runtime/store.py:406)
_.persist_checkpoint  # unused method (src/wilted/station_runtime/store.py:411)
_.append_event  # unused method (src/wilted/station_runtime/store.py:427)
_.persist_lease  # unused method (src/wilted/station_runtime/store.py:458)
_.last_poll_at  # unused property (src/wilted/station_runtime/weather_monitor.py:618)
_.consecutive_failures  # unused property (src/wilted/station_runtime/weather_monitor.py:636)
TITLE  # unused variable (src/wilted/tui/__init__.py:200)
DEFAULT_CSS  # unused variable (src/wilted/tui/__init__.py:202)
BINDINGS  # unused variable (src/wilted/tui/__init__.py:281)
_.theme  # unused attribute (src/wilted/tui/__init__.py:315)
_._briefing_started  # unused attribute (src/wilted/tui/__init__.py:382)
_.compose  # unused method (src/wilted/tui/__init__.py:449)
_.on_mount  # unused method (src/wilted/tui/__init__.py:470)
_._briefing_started  # unused attribute (src/wilted/tui/__init__.py:508)
_.on_unmount  # unused method (src/wilted/tui/__init__.py:524)
_.display  # unused attribute (src/wilted/tui/__init__.py:637)
_.display  # unused attribute (src/wilted/tui/__init__.py:643)
_.show_root  # unused attribute (src/wilted/tui/__init__.py:817)
_.display  # unused attribute (src/wilted/tui/__init__.py:980)
_.display  # unused attribute (src/wilted/tui/__init__.py:983)
_.display  # unused attribute (src/wilted/tui/__init__.py:986)
_.action_warm_daemon  # unused method (src/wilted/tui/__init__.py:1262)
_.on_playback_completed  # unused method (src/wilted/tui/__init__.py:1826)
_.on_route_changed  # unused method (src/wilted/tui/__init__.py:1933)
_.action_play_selected  # unused method (src/wilted/tui/__init__.py:2138)
_.action_skip_segment  # unused method (src/wilted/tui/__init__.py:2144)
_.action_prev_paragraph  # unused method (src/wilted/tui/__init__.py:2160)
_.action_speed_down  # unused method (src/wilted/tui/__init__.py:2181)
_.action_speed_up  # unused method (src/wilted/tui/__init__.py:2187)
_.action_next_article  # unused method (src/wilted/tui/__init__.py:2193)
_.action_voice_settings  # unused method (src/wilted/tui/__init__.py:2203)
_.action_add_article  # unused method (src/wilted/tui/__init__.py:2221)
_.action_mark_read  # unused method (src/wilted/tui/__init__.py:2253)
_.action_delete_selected  # unused method (src/wilted/tui/__init__.py:2285)
_.action_text_preview  # unused method (src/wilted/tui/__init__.py:2323)
_.action_clear_all  # unused method (src/wilted/tui/__init__.py:2343)
_.action_refresh_queue  # unused method (src/wilted/tui/__init__.py:2373)
_.action_quit_app  # unused method (src/wilted/tui/__init__.py:2378)
_.action_export_wav  # unused method (src/wilted/tui/__init__.py:2393)
DEFAULT_CSS  # unused variable (src/wilted/tui/screens/add_article.py:23)
BINDINGS  # unused variable (src/wilted/tui/screens/add_article.py:68)
_.compose  # unused method (src/wilted/tui/screens/add_article.py:73)
_.on_mount  # unused method (src/wilted/tui/screens/add_article.py:85)
_.on_input_submitted  # unused method (src/wilted/tui/screens/add_article.py:88)
_._add_to_queue  # unused method (src/wilted/tui/screens/add_article.py:92)
_._add_and_play  # unused method (src/wilted/tui/screens/add_article.py:96)
_._add_cancel  # unused method (src/wilted/tui/screens/add_article.py:100)
_.action_play_after  # unused method (src/wilted/tui/screens/add_article.py:105)
DEFAULT_CSS  # unused variable (src/wilted/tui/screens/confirm.py:19)
BINDINGS  # unused variable (src/wilted/tui/screens/confirm.py:55)
_.compose  # unused method (src/wilted/tui/screens/confirm.py:65)
_.on_button_pressed  # unused method (src/wilted/tui/screens/confirm.py:80)
DEFAULT_CSS  # unused variable (src/wilted/tui/screens/report.py:38)
BINDINGS  # unused variable (src/wilted/tui/screens/report.py:84)
_.compose  # unused method (src/wilted/tui/screens/report.py:102)
_.on_mount  # unused method (src/wilted/tui/screens/report.py:112)
_.cursor_type  # unused attribute (src/wilted/tui/screens/report.py:114)
_.zebra_stripes  # unused attribute (src/wilted/tui/screens/report.py:115)
_.on_resize  # unused method (src/wilted/tui/screens/report.py:241)
_.on_data_table_row_selected  # unused method (src/wilted/tui/screens/report.py:234)
_.action_select_all  # unused method (src/wilted/tui/screens/report.py:246)
_.action_select_none  # unused method (src/wilted/tui/screens/report.py:252)
_._done_button  # unused method (src/wilted/tui/screens/report.py:385)
DEFAULT_CSS  # unused variable (src/wilted/tui/screens/text_preview.py:19)
BINDINGS  # unused variable (src/wilted/tui/screens/text_preview.py:58)
_.compose  # unused method (src/wilted/tui/screens/text_preview.py:68)
_.on_button_pressed  # unused method (src/wilted/tui/screens/text_preview.py:80)
DEFAULT_CSS  # unused variable (src/wilted/tui/screens/voice_settings.py:21)
BINDINGS  # unused variable (src/wilted/tui/screens/voice_settings.py:80)
_.compose  # unused method (src/wilted/tui/screens/voice_settings.py:97)
_.on_mount  # unused method (src/wilted/tui/screens/voice_settings.py:115)
_.cursor_type  # unused attribute (src/wilted/tui/screens/voice_settings.py:117)
_.on_data_table_row_selected  # unused method (src/wilted/tui/screens/voice_settings.py:127)
_.on_data_table_row_highlighted  # unused method (src/wilted/tui/screens/voice_settings.py:130)
_.action_speed_down  # unused method (src/wilted/tui/screens/voice_settings.py:136)
_.action_speed_up  # unused method (src/wilted/tui/screens/voice_settings.py:140)
_.action_lang_a  # unused method (src/wilted/tui/screens/voice_settings.py:148)
_.action_lang_b  # unused method (src/wilted/tui/screens/voice_settings.py:151)
_.action_lang_j  # unused method (src/wilted/tui/screens/voice_settings.py:154)
_.action_lang_z  # unused method (src/wilted/tui/screens/voice_settings.py:157)
_.on_button_pressed  # unused method (src/wilted/tui/screens/voice_settings.py:166)
