#!/usr/bin/env python3
"""Disposable pairing/transport-security spike — Task 0.5 (MAC-SIDE).

**This is a disposable spike. It is not production code.** See
``THREAT-MODEL.md`` in this directory for the full threat model and the
open-decision-#1 analysis (native macOS companion vs. one approved Python
Keychain/TLS dependency) this spike is meant to inform.

Proves, end to end, against a real localhost TLS server:

1. **ONE-TIME ENROLLMENT** — a pairing token enrolls a client exactly once;
   a second enrollment attempt with the same token is rejected (replay /
   double-enroll defense).
2. **AUTHENTICATED TRANSPORT** — an unauthenticated client (no/garbage
   credential) cannot fetch the station manifest or any asset.
3. **STALE-REVISION REJECTION** — a request presenting an
   ``expected_revision`` behind the server's current revision is rejected
   before any state is read back, mirroring the idempotent-write contract
   already enforced by the committed reducer
   (``wilted.station.reducer.Checkpoint.expected_revision``).
4. **ASSET-HASH REJECTION** — a request presenting a tampered/wrong asset
   hash is rejected; no asset bytes are ever returned for a hash mismatch.
5. **SECRET HYGIENE** — nothing generated by this spike (pairing token,
   per-client HMAC credential, TLS private key) ever touches a file under
   the repository working tree, ever appears in captured stdout/stderr, or
   ever appears in the log stream. Everything sensitive lives only under
   one ``tempfile.mkdtemp()`` directory, which is shredded in ``finally``.

Design notes (see THREAT-MODEL.md for the full writeup):

- The TLS server certificate/key are generated **once**, for this run
  only, via the macOS-bundled ``openssl`` CLI (subprocess), writing
  directly into the ephemeral temp dir. This spike does not use
  ``cryptography`` or any other non-stdlib Python dependency — it proves
  the *protocol* properties without deciding open-decision #1's dependency
  question. If a future spike needs certificate extensions ``openssl``
  can't express conveniently, that is itself evidence for the
  ``cryptography`` side of that decision (noted in THREAT-MODEL.md).
- Client authentication is **application-layer** (HMAC over method + path
  + expected_revision + timestamp + nonce, keyed by a per-client secret
  issued at enrollment), not X.509 client certificates. TLS here provides
  confidentiality/server-authenticity and defeats passive LAN
  eavesdropping + naive MITM; the HMAC layer provides per-client
  authentication and replay resistance. See THREAT-MODEL.md's transport
  recommendation for why full mTLS is not attempted in this spike.
- Discovery (Bonjour/``_wilted._tcp``) is simulated by hardcoding
  ``localhost`` — no real mDNS stack is stood up (YAGNI per the task
  brief: "no real Bonjour/mDNS stack needed").
- Real Keychain storage is NOT exercised against the login keychain. See
  THREAT-MODEL.md's "Open decision #1" section for the documented
  ``keyring``-backed approach; this spike stores the per-client credential
  only in an in-memory dict and the ephemeral temp dir, standing in for
  "Keychain-shaped" storage without touching the actual OS keychain.

Usage:
    python spikes/pairing-security-2026-07-10/pairing_spike.py

Exits 0 with every property PASS; exits 1 (non-zero) if any property
fails. This script is a CLI entry point, not an importable library module,
so it prints status lines rather than logging (matches project convention:
"CLI commands can print") — but never prints secret material; see
``SECRET HYGIENE`` below and its enforcement in ``main()``.
"""

from __future__ import annotations

import hashlib
import hmac
import http.client
import json
import math
import secrets
import shutil
import socket
import ssl
import subprocess
import sys
import tempfile
import threading
import time
import uuid
from dataclasses import dataclass, field
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
SPIKE_DIR = Path(__file__).resolve().parent

# ---------------------------------------------------------------------------
# Ephemeral TLS identity generation (openssl CLI, never a Python dependency)
# ---------------------------------------------------------------------------


def generate_ephemeral_tls_identity(temp_dir: Path) -> tuple[Path, Path]:
    """Generate a self-signed cert/key pair into ``temp_dir`` via ``openssl``.

    Uses the macOS-bundled ``openssl`` CLI so this spike adds zero Python
    dependencies. The key/cert are written only under ``temp_dir`` (never
    under the repo) and are the caller's responsibility to shred.

    Args:
        temp_dir: Ephemeral directory to write ``server.key``/``server.crt``
            into. Must already exist.

    Returns:
        ``(key_path, cert_path)``.

    Raises:
        RuntimeError: If the ``openssl`` subprocess fails or is not found.
    """
    key_path = temp_dir / "server.key"
    cert_path = temp_dir / "server.crt"
    try:
        subprocess.run(
            [
                "openssl",
                "req",
                "-x509",
                "-newkey",
                "ec",
                "-pkeyopt",
                "ec_paramgen_curve:prime256v1",
                "-keyout",
                str(key_path),
                "-out",
                str(cert_path),
                "-days",
                "1",
                "-nodes",
                "-subj",
                "/CN=wilted-station-spike.local",
            ],
            check=True,
            capture_output=True,
            timeout=30,
        )
    except FileNotFoundError as exc:
        raise RuntimeError("openssl CLI not found; required to generate the ephemeral TLS identity") from exc
    except subprocess.CalledProcessError as exc:
        # Deliberately do not include exc.stdout/exc.stderr verbatim in any
        # exception message that might get logged/printed — openssl error
        # output does not contain key material for a *failed* keygen, but
        # we keep this defensive per the "print no secret material, ever"
        # requirement.
        raise RuntimeError(f"openssl cert generation failed (exit {exc.returncode})") from exc
    if not key_path.exists() or not cert_path.exists():
        raise RuntimeError("openssl did not produce the expected key/cert files")
    return key_path, cert_path


# ---------------------------------------------------------------------------
# In-memory "station" fixture — plain-JSON manifest/asset shape
# ---------------------------------------------------------------------------


@dataclass
class FixtureAsset:
    """One media asset the manifest references, with its content hash."""

    asset_id: str
    content: bytes
    sha256: str = field(init=False)

    def __post_init__(self) -> None:
        self.sha256 = hashlib.sha256(self.content).hexdigest()


def build_fixture_manifest_and_asset() -> tuple[dict[str, Any], FixtureAsset]:
    """Build a minimal plain-JSON manifest + one asset, shaped like ``StationCore.get_manifest()``.

    Mirrors the read-surface shape in
    ``spikes/mac-substrate-2026-07-10/candidate_a/core.py:115-149`` (schema
    version, station revision, active entry summary with a media hash) —
    this spike does not import that module (YAGNI: no reducer wiring needed
    to prove transport-security properties), it only matches the JSON
    shape a real client would authenticate against.
    """
    asset = FixtureAsset(asset_id="entry-1-media", content=b"not real audio bytes, just a fixture payload")
    manifest = {
        "schema_version": 1,
        "station_revision": 1,
        "lifecycle": "playing",
        "active_entry": {
            "entry_id": "entry-1",
            "kind": "item",
            "media": {"asset_id": asset.asset_id, "sha256": asset.sha256, "byte_size": len(asset.content)},
        },
    }
    return manifest, asset


# ---------------------------------------------------------------------------
# Pairing/enrollment state (server-side, in-memory + ephemeral temp dir only)
# ---------------------------------------------------------------------------


class PairingStore:
    """Server-side pairing/enrollment state.

    All secret values (pairing token, per-client HMAC credentials) live
    only as attributes of this object (process memory) and are never
    written to any file under the repo. A "Keychain-shaped" ephemeral
    marker file is written under ``temp_dir`` purely to demonstrate where
    a real implementation would hand the credential to ``keyring``/the
    Keychain — see THREAT-MODEL.md's open-decision-#1 section. The login
    keychain is never touched.
    """

    def __init__(self, temp_dir: Path) -> None:
        self._temp_dir = temp_dir
        self._pairing_token = secrets.token_urlsafe(32)
        self._token_consumed = False
        self._lock = threading.Lock()
        # holder_id -> per-client HMAC credential (bytes)
        self._enrolled_clients: dict[str, bytes] = {}
        # seen (holder_id, nonce) pairs, for replay resistance on
        # authenticated requests (distinct from one-time *enrollment*)
        self._seen_nonces: set[tuple[str, str]] = set()

    @property
    def pairing_token(self) -> str:
        """The single-use enrollment token. Test-driver-only access; never logged/printed."""
        return self._pairing_token

    def enroll(self, presented_token: str, holder_id: str) -> bytes | None:
        """Attempt one-time enrollment.

        Returns the newly issued per-client HMAC credential on success, or
        None if the token is wrong or has already been consumed (by this
        or any other holder_id — the token is single-use *globally*, not
        per-client, matching "a pairing token cannot enroll twice").
        """
        with self._lock:
            if self._token_consumed:
                return None
            if not hmac.compare_digest(presented_token, self._pairing_token):
                return None
            credential = secrets.token_bytes(32)
            self._enrolled_clients[holder_id] = credential
            self._token_consumed = True
            # Demonstrate "Keychain-shaped" ephemeral custody: a real
            # implementation hands `credential` to `keyring.set_password(...)`
            # here instead of writing a marker file. We write only a
            # non-secret marker (holder_id, no credential bytes) so the
            # temp-dir listing has *something* to shred, without ever
            # putting the credential itself on disk anywhere, including
            # under the ephemeral dir.
            marker = self._temp_dir / f"enrolled-{holder_id}.marker"
            marker.write_text("enrolled (credential held only in process memory, not on disk)\n")
            return credential

    def credential_for(self, holder_id: str) -> bytes | None:
        return self._enrolled_clients.get(holder_id)

    def nonce_seen(self, holder_id: str, nonce: str) -> bool:
        """Return True if ``(holder_id, nonce)`` has already been recorded.

        Non-mutating: callers must not treat a False result as permission
        to skip calling :meth:`record_nonce` — the two are split
        deliberately so a request can be checked for replay *and* have its
        signature verified before the nonce is burned (see
        ``_authenticate``: recording a nonce for a request that turns out
        to have a bad signature would let an attacker who never had the
        credential burn nonces the legitimate client would otherwise use).
        """
        with self._lock:
            return (holder_id, nonce) in self._seen_nonces

    def record_nonce(self, holder_id: str, nonce: str) -> None:
        """Record ``(holder_id, nonce)`` as seen, after signature verification succeeds."""
        with self._lock:
            self._seen_nonces.add((holder_id, nonce))

    def all_secret_values(self) -> list[str]:
        """Every secret string this store has ever generated, for hygiene scanning only.

        Used exclusively by ``assert_no_secret_leak`` in this spike's
        test driver — never printed, logged, or written anywhere else.
        """
        values = [self._pairing_token]
        for credential in self._enrolled_clients.values():
            values.append(credential.hex())
        return values


# ---------------------------------------------------------------------------
# HTTP/TLS request handling
# ---------------------------------------------------------------------------


def _sign(credential: bytes, method: str, path: str, expected_revision: int, timestamp: str, nonce: str) -> str:
    """Compute the HMAC-SHA256 signature a client attaches to an authenticated request."""
    message = f"{method}|{path}|{expected_revision}|{timestamp}|{nonce}".encode()
    return hmac.new(credential, message, hashlib.sha256).hexdigest()


class StationRequestHandler(BaseHTTPRequestHandler):
    """Minimal handler: POST /enroll, GET /manifest, GET /asset.

    ``server`` is a :class:`_StationHTTPServer`, which carries the shared
    ``PairingStore`` and fixture manifest/asset.
    """

    server: _StationHTTPServer  # type: ignore[assignment]

    def log_message(self, format: str, *args: Any) -> None:  # noqa: A002
        """Suppress BaseHTTPRequestHandler's default stderr access log.

        The default implementation prints request lines (including the
        full path, which carries the HMAC signature and nonce — not the
        credential itself, but still request material we don't want on
        stdout/stderr per the "print no secret material" requirement).
        This spike's driver captures pass/fail via return values, not log
        scraping, so suppressing this is safe and correct.
        """

    def _send_json(self, status: int, payload: dict[str, Any] | None) -> None:
        body = json.dumps(payload).encode() if payload is not None else b""
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        if body:
            self.wfile.write(body)

    def _authenticate(self) -> str | None:
        """Return the authenticated holder_id, or None if auth fails.

        Expects headers ``X-Holder-Id``, ``X-Timestamp``, ``X-Nonce``,
        ``X-Signature``. Rejects: unknown holder, non-finite/stale
        timestamp, replayed nonce, or bad signature. Timestamp freshness
        (+/- 30s) additionally bounds replay of an
        intercepted-but-not-yet-used request.

        Order matters here: the nonce is only *recorded* (burned) after
        the HMAC signature has been verified. Checking-without-recording
        happens earlier so a replayed nonce is still rejected even with a
        valid signature, but a request with an invalid signature can never
        consume/burn a nonce the legitimate client would otherwise need —
        otherwise an on-path attacker who merely knows an enrolled
        ``holder_id`` (not secret) could DoS the nonce namespace with
        garbage signatures.
        """
        holder_id = self.headers.get("X-Holder-Id", "")
        timestamp = self.headers.get("X-Timestamp", "")
        nonce = self.headers.get("X-Nonce", "")
        signature = self.headers.get("X-Signature", "")
        if not (holder_id and timestamp and nonce and signature):
            return None
        credential = self.server.pairing_store.credential_for(holder_id)
        if credential is None:
            return None
        try:
            ts = float(timestamp)
        except ValueError:
            return None
        if not math.isfinite(ts) or abs(time.time() - ts) > 30:
            return None
        if self.server.pairing_store.nonce_seen(holder_id, nonce):
            return None
        expected_revision = self.headers.get("X-Expected-Revision", "-1")
        expected_signature = _sign(credential, self.command, self.path, int(expected_revision), timestamp, nonce)
        if not hmac.compare_digest(signature, expected_signature):
            return None
        self.server.pairing_store.record_nonce(holder_id, nonce)
        return holder_id

    def do_POST(self) -> None:  # noqa: N802
        if self.path == "/enroll":
            length = int(self.headers.get("Content-Length", "0"))
            raw = self.rfile.read(length) if length else b"{}"
            try:
                payload = json.loads(raw)
            except json.JSONDecodeError:
                self._send_json(400, {"error": "bad_request"})
                return
            presented_token = payload.get("token", "")
            holder_id = payload.get("holder_id", "")
            if not presented_token or not holder_id:
                self._send_json(400, {"error": "bad_request"})
                return
            credential = self.server.pairing_store.enroll(presented_token, holder_id)
            if credential is None:
                self._send_json(403, {"error": "enrollment_rejected"})
                return
            # The credential is returned exactly once, over TLS, to the
            # enrolling client only — this is the one point in the whole
            # protocol where it crosses the wire. It is never logged,
            # never printed, and the response body is not written to any
            # file by either side of this spike.
            self._send_json(200, {"credential_hex": credential.hex()})
            return
        self._send_json(404, {"error": "not_found"})

    def do_GET(self) -> None:  # noqa: N802
        holder_id = self._authenticate()
        if holder_id is None:
            self._send_json(403, None)  # No manifest, no asset, no body at all.
            return

        if self.path.startswith("/manifest"):
            query_revision = _query_param(self.path, "expected_revision")
            if query_revision is not None and int(query_revision) < self.server.manifest["station_revision"]:
                self._send_json(409, {"error": "stale_revision"})
                return
            self._send_json(200, self.server.manifest)
            return

        if self.path.startswith("/asset"):
            expected_hash = _query_param(self.path, "expected_sha256")
            if expected_hash is None or not hmac.compare_digest(expected_hash, self.server.asset.sha256):
                self._send_json(409, {"error": "asset_hash_mismatch"})
                return
            self.send_response(200)
            self.send_header("Content-Type", "application/octet-stream")
            self.send_header("Content-Length", str(len(self.server.asset.content)))
            self.end_headers()
            self.wfile.write(self.server.asset.content)
            return

        self._send_json(404, {"error": "not_found"})


def _query_param(path: str, name: str) -> str | None:
    if "?" not in path:
        return None
    _, _, query = path.partition("?")
    for part in query.split("&"):
        key, _, value = part.partition("=")
        if key == name:
            return value
    return None


class _StationHTTPServer(HTTPServer):
    """HTTPServer subclass carrying the shared pairing store + fixture data."""

    def __init__(self, address: tuple[str, int], pairing_store: PairingStore, manifest: dict, asset: FixtureAsset):
        super().__init__(address, StationRequestHandler)
        self.pairing_store = pairing_store
        self.manifest = manifest
        self.asset = asset


# ---------------------------------------------------------------------------
# Minimal authenticated client (stands in for the iPhone/native client)
# ---------------------------------------------------------------------------


class SpikeClient:
    """A minimal authenticated HTTPS client for this spike's protocol."""

    def __init__(self, host: str, port: int, ssl_context: ssl.SSLContext, holder_id: str) -> None:
        self.host = host
        self.port = port
        self._ssl_context = ssl_context
        self.holder_id = holder_id
        self._credential: bytes | None = None

    def enroll(self, token: str) -> bool:
        conn = http.client.HTTPSConnection(self.host, self.port, context=self._ssl_context, timeout=5)
        try:
            body = json.dumps({"token": token, "holder_id": self.holder_id}).encode()
            conn.request("POST", "/enroll", body=body, headers={"Content-Type": "application/json"})
            resp = conn.getresponse()
            data = json.loads(resp.read())
            if resp.status != 200:
                return False
            self._credential = bytes.fromhex(data["credential_hex"])
            return True
        finally:
            conn.close()

    def _authenticated_get(self, path: str, expected_revision: int = -1) -> http.client.HTTPResponse:
        conn = http.client.HTTPSConnection(self.host, self.port, context=self._ssl_context, timeout=5)
        headers = self._auth_headers("GET", path, expected_revision)
        conn.request("GET", path, headers=headers)
        return conn.getresponse()

    def _auth_headers(self, method: str, path: str, expected_revision: int) -> dict[str, str]:
        if self._credential is None:
            # Unauthenticated caller: send garbage/absent auth headers on
            # purpose, to exercise the AUTHENTICATED TRANSPORT rejection
            # path from the client side.
            return {}
        timestamp = f"{time.time():.6f}"
        nonce = uuid.uuid4().hex
        signature = _sign(self._credential, method, path, expected_revision, timestamp, nonce)
        return {
            "X-Holder-Id": self.holder_id,
            "X-Timestamp": timestamp,
            "X-Nonce": nonce,
            "X-Expected-Revision": str(expected_revision),
            "X-Signature": signature,
        }

    def fetch_manifest(self, expected_revision: int) -> tuple[int, bytes]:
        resp = self._authenticated_get(f"/manifest?expected_revision={expected_revision}", expected_revision)
        return resp.status, resp.read()

    def fetch_asset(self, expected_sha256: str, expected_revision: int = 1) -> tuple[int, bytes]:
        resp = self._authenticated_get(f"/asset?expected_sha256={expected_sha256}", expected_revision)
        return resp.status, resp.read()


# ---------------------------------------------------------------------------
# Test driver
# ---------------------------------------------------------------------------


@dataclass
class PropertyResult:
    name: str
    passed: bool
    detail: str


def _free_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.bind(("127.0.0.1", 0))
        return sock.getsockname()[1]


def run_spike(temp_dir: Path) -> list[PropertyResult]:
    """Run the full pairing/transport spike and return per-property results."""
    results: list[PropertyResult] = []

    key_path, cert_path = generate_ephemeral_tls_identity(temp_dir)

    manifest, asset = build_fixture_manifest_and_asset()
    pairing_store = PairingStore(temp_dir)

    server_ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    server_ctx.load_cert_chain(certfile=str(cert_path), keyfile=str(key_path))

    port = _free_port()
    httpd = _StationHTTPServer(("127.0.0.1", port), pairing_store, manifest, asset)
    httpd.socket = server_ctx.wrap_socket(httpd.socket, server_side=True)

    server_thread = threading.Thread(target=httpd.serve_forever, daemon=True)
    server_thread.start()
    try:
        client_ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
        # Certificate verification stays ON (CERT_REQUIRED is
        # PROTOCOL_TLS_CLIENT's default and is asserted explicitly below,
        # never weakened to CERT_NONE): trust is pinned to exactly this
        # run's ephemeral self-signed cert via load_verify_locations, so
        # any connection presenting a different certificate is rejected.
        # Only hostname matching is skipped, because this spike connects
        # to a literal loopback IP, not the cert's CN
        # ("wilted-station-spike.local") — that is a hostname-match
        # concern, not a trust concern, and is orthogonal to
        # verify_mode/CERT_REQUIRED.
        client_ctx.load_verify_locations(cafile=str(cert_path))
        client_ctx.verify_mode = ssl.CERT_REQUIRED
        client_ctx.check_hostname = False

        # -- Property 1: ONE-TIME ENROLLMENT ---------------------------------
        phone = SpikeClient("127.0.0.1", port, client_ctx, holder_id="iphone-spike")
        first_enroll_ok = phone.enroll(pairing_store.pairing_token)
        attacker_replay = SpikeClient("127.0.0.1", port, client_ctx, holder_id="attacker-replay")
        second_enroll_ok = attacker_replay.enroll(pairing_store.pairing_token)
        one_time_enrollment_ok = first_enroll_ok is True and second_enroll_ok is False
        results.append(
            PropertyResult(
                "ONE-TIME ENROLLMENT",
                one_time_enrollment_ok,
                f"first_enroll={first_enroll_ok} second_enroll_with_same_token={second_enroll_ok} "
                "(expected True, False)",
            )
        )

        # -- Property 2: AUTHENTICATED TRANSPORT -----------------------------
        unauthenticated = SpikeClient("127.0.0.1", port, client_ctx, holder_id="unpaired-client")
        status_unauth, body_unauth = unauthenticated.fetch_manifest(expected_revision=1)
        status_auth, body_auth = phone.fetch_manifest(expected_revision=1)
        authenticated_transport_ok = (
            status_unauth == 403 and body_unauth == b"" and status_auth == 200 and json.loads(body_auth)
        )
        results.append(
            PropertyResult(
                "AUTHENTICATED TRANSPORT",
                bool(authenticated_transport_ok),
                f"unauthenticated -> status={status_unauth} body_len={len(body_unauth)} (expected 403, 0 bytes); "
                f"authenticated -> status={status_auth} (expected 200 with manifest body)",
            )
        )

        # -- Property 3: STALE-REVISION REJECTION ----------------------------
        status_stale, body_stale = phone.fetch_manifest(expected_revision=0)  # current revision is 1
        status_current, _ = phone.fetch_manifest(expected_revision=1)
        stale_revision_ok = status_stale == 409 and status_current == 200
        results.append(
            PropertyResult(
                "STALE-REVISION REJECTION",
                stale_revision_ok,
                f"stale request (expected_revision=0 < current=1) -> status={status_stale} (expected 409); "
                f"current-revision request -> status={status_current} (expected 200)",
            )
        )

        # -- Property 4: ASSET-HASH REJECTION ---------------------------------
        tampered_hash = "0" * 64
        status_tampered, body_tampered = phone.fetch_asset(tampered_hash)
        status_valid, body_valid = phone.fetch_asset(asset.sha256)
        asset_hash_ok = (
            status_tampered == 409
            and body_tampered != asset.content
            and status_valid == 200
            and body_valid == asset.content
        )
        results.append(
            PropertyResult(
                "ASSET-HASH REJECTION",
                asset_hash_ok,
                f"tampered hash -> status={status_tampered} (expected 409, no asset bytes); "
                f"correct hash -> status={status_valid} bytes_match={body_valid == asset.content} (expected 200, True)",
            )
        )

        return results, pairing_store  # type: ignore[return-value]
    finally:
        httpd.shutdown()
        httpd.server_close()
        server_thread.join(timeout=5)


def assert_no_secret_leak(secret_values: list[str], captured_stdio: str) -> PropertyResult:
    """Grep-scan the repo tree and captured stdio for any generated secret substring.

    Args:
        secret_values: Every secret string/hex-encoded value this run
            generated (pairing token, per-client credentials).
        captured_stdio: Everything this script itself printed to
            stdout/stderr during the run (captured by ``main()``).

    Returns:
        A :class:`PropertyResult` — FAILS loudly (never prints the actual
        secret value in its detail message) if any secret substring is
        found anywhere it must not be.
    """
    problems: list[str] = []

    for value in secret_values:
        if not value:
            continue
        if value in captured_stdio:
            problems.append("a generated secret value was found in this script's own stdout/stderr")
            break

    # Scan every tracked-looking file under the repo working tree (source,
    # docs, config — anything that isn't inside the ephemeral temp dir,
    # which lives outside REPO_ROOT under the OS temp root).
    text_suffixes = {".py", ".md", ".toml", ".json", ".txt", ".cfg", ".ini", ".yaml", ".yml", ".log"}
    for path in REPO_ROOT.rglob("*"):
        if not path.is_file():
            continue
        if path.suffix not in text_suffixes:
            continue
        # Skip virtualenvs/build artifacts/VCS internals — never secret
        # material, and scanning them is slow and irrelevant.
        parts = set(path.parts)
        if parts & {".venv", ".git", "build", "__pycache__", ".pytest_cache", ".ruff_cache"}:
            continue
        try:
            contents = path.read_text(errors="ignore")
        except OSError:
            continue
        for value in secret_values:
            if value and value in contents:
                problems.append(f"a generated secret value was found in repo file: {path.relative_to(REPO_ROOT)}")

    if problems:
        return PropertyResult("SECRET HYGIENE", False, "; ".join(problems))
    return PropertyResult(
        "SECRET HYGIENE",
        True,
        f"scanned {len(secret_values)} generated secret value(s) against this script's own stdio output "
        f"and every text file under {REPO_ROOT} — none found outside the ephemeral temp dir",
    )


def main() -> int:
    temp_dir = Path(tempfile.mkdtemp(prefix="wilted-pairing-spike-"))
    results: list[PropertyResult] = []
    secret_values: list[str] = []
    try:
        run_output, pairing_store = run_spike(temp_dir)
        results.extend(run_output)
        secret_values = pairing_store.all_secret_values()
    except Exception as exc:  # noqa: BLE001 - a spike-infrastructure failure is itself a FAIL row
        results.append(PropertyResult("SPIKE EXECUTION", False, f"{type(exc).__name__}: {exc}"))
    finally:
        # SECRET HYGIENE is asserted regardless of whether the rest of the
        # spike succeeded, then the temp dir is shredded unconditionally.
        stdio_so_far = "\n".join(f"{r.name}: {'PASS' if r.passed else 'FAIL'} - {r.detail}" for r in results)
        results.append(assert_no_secret_leak(secret_values, stdio_so_far))
        shutil.rmtree(temp_dir, ignore_errors=True)

    print("Pairing/transport-security spike (Task 0.5) — disposable, see THREAT-MODEL.md\n")
    all_passed = True
    for result in results:
        status = "PASS" if result.passed else "FAIL"
        if not result.passed:
            all_passed = False
        print(f"[{status}] {result.name}: {result.detail}")

    print()
    if all_passed:
        print("ALL PROPERTIES PASSED. Ephemeral temp dir shredded. No secret material printed above.")
        return 0
    print("ONE OR MORE PROPERTIES FAILED. See detail lines above.")
    return 1


if __name__ == "__main__":
    sys.exit(main())
